src/Entity/Auteur.php
<?php

namespace App\Entity;

use App\Repository\AuteurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=AuteurRepository::class)
 */
class Auteur
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\Length(
     *     min="3",
     *     max="255",
     *     minMessage = "Your first name must be at least {{ limit }} characters long",
     *     maxMessage = "Your first name cannot be longer than {{ limit }} characters"
     * )
     * @Assert\Regex(
     *  pattern = "/\d/",
     *   match = false
     * )
     *
     * @ORM\Column(type="string", length=100)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $prenom;

    /**
     * @ORM\Column(type="date")
     */
    private $anniversaire;

    /**
     * @ORM\ManyToMany(targetEntity=Book::class, mappedBy="auteurs")
     */
    private $books;

    public function __construct()
    {
        $this->books = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getAnniversaire(): ?\DateTimeInterface
    {
        return $this->anniversaire;
    }

    public function setAnniversaire(\DateTimeInterface $anniversaire): self
    {
        $this->anniversaire = $anniversaire;

        return $this;
    }

    /**
     * @return Collection<int, Book>
     */
    public function getBooks(): Collection
    {
        return $this->books;
    }

    public function addBook(Book $book): self
    {
        if (!$this->books->contains($book)) {
            $this->books[] = $book;
            $book->addAuteur($this);
        }

        return $this;
    }

    public function removeBook(Book $book): self
    {
        if ($this->books->removeElement($book)) {
            $book->removeAuteur($this);
        }

        return $this;
    }

    /**
     * @return string
     */
    public function getFullName(): ?string
    {
        return $this->getNom(). " " . $this->getPrenom();
    }
}

templates/front/article.html.twig
{% extends "base.html.twig" %}

{% block title %}Article{% endblock %}

{% block body %}
    <header class="segment ui raised center aligned green">
        <h2>{{ article.titre }}</h2> {# récupération du titre #}

    </header>
    <p>
    {{ include("front/template_part/_menu.html.twig",{currentPage: 0}) }}
        <a href='{{ path('home') }}' class="ui button">retour</a>
    </p>
    <p class="" style="text-align: right;">
        écrit par {{ article.auteur }} le {{ article.dateArt|date("d-m-Y") }}</p>
    <p>
        {{ article.content }}
    </p>

{% endblock %}

templates/front/home.html.twig
{% extends "base.html.twig" %}

{% block title %}Page d'accueil{% endblock %}

{% block body %}
    <header class="segment ui raised center aligned violet">
        <h2>{{ titre }}</h2> {# récupérlisteArticlesation du titre #}
    </header>
    <p>
        {{ include("front/template_part/_menu.html.twig",{currentPage: 0}) }}
{#        {% for val in tableau %} #}{# boucle mon tableau d'arguments  #}
{#            {% if val matches '/^\\d+$/' %}#}
{#                <a href="{{ path("app_page", { numPage: val }) }}">un lien page</a>#}
{#            {% else %}#}
{#                <a href="{{ path("app_slug", { slug: val }) }}">un lien slug</a>#}
{#            {% endif %}#}
{#            <a href="/page/{{ val }}">Page {{ val }}</a>&nbsp;#}
{#        {% endfor %}#}
    </p>
{#    <p><a href='/page/1'>Page 1</a>&nbsp; <a href='/page/2'>Page 2</a></p>#}
    <h5>Articles</h5>
{#    {{ render(path("listeArticles")) }}#}
    {{ render(controller('App\\Controller\\HomeController::listeArticles')) }}
{#    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.#}
{#        Accusantium alias commodi deserunt eius eligendi esse facere,#}
{#        impedit labore nemo placeat repudiandae tenetur, ut? Ea illo,#}
{#        molestiae officia quo similique voluptate.</p>#}
{% endblock %}

templates/front/listeBook.html.twig
{% extends "base.html.twig" %}

{% block title %}Liste livre{% endblock %}

{% block body %}
<header class="segment ui raised center aligned blue">
    <h2>Catalogue livre</h2>
</header>
    {% for message in app.flashes('success') %}
        <div class="">{{ message }}</div>
    {% endfor %}
    <div class="flexbutton mb">
        <a href="{{ path("bookedit",{id: -1}) }}" class="ui button">Nouveau livre</a>
        <a href="{{ path("auteuredit",{id: -1}) }}" class="ui button">Nouvel auteur</a>
    </div>
    <div class="ui cards">
        {% for book in books %}
            <div class="card">
                <div class="content">
                    <div class="header">
                      {{ book.titre}}
                    </div>
                    <div class="meta">
                        {% for auteur in book.auteurs %}
                            {{ auteur.fullName }}&nbsp;
                        {% endfor %}
                    </div>
                    <div class="meta" style="text-align: right">
                        {{ book.genre.category }}
                    </div>
                    <div class="description">
                        {{ book.description }}
                    </div>
                    <div class="footer flexbutton">
                        <a href="{{ path("bookedit", {id: book.id}) }}"
                           class="ui button">modifier</a>&nbsp;
                        <form action="{{ path("deletebook", {id: book.id}) }}"
                              method="post" onsubmit="return confirm('Etes-vous sûre de vous ?');">
                            <input type="hidden" name="_token"
                                   value="{{ csrf_token('delete'~book.id) }}">
                            <button type="submit" class="ui button">Del</button>
                        </form>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>


{% endblock %}

templates/front/listeFiltre.html.twig
{% extends "base.html.twig" %}

{% block title %}Articles filtrés{% endblock %}

{% block body %}
<header class="segment ui raised center aligned orange">
    <h2>Articles Filtrés</h2> {# récupérlisteArticlesation du titre #}
</header>
    <h5>Articles</h5>
    {{ include("front/template_part/_listeArticles.html.twig", {articles: articles}) }}
{% endblock %}

templates/front/page.html.twig
{% extends "base.html.twig" %}

{% block title %}Page {{ numPage }}{% endblock %}
{% block body %}
    <header class="segment ui raised center aligned red">
        <h2>Vous êtes sur la page {{ numPage }}</h2> {# récupération du titre #}
    </header>

    <p>
        {{ include("front/template_part/_menu.html.twig",{currentPage: numPage}) }}
        <a href='{{ path('home') }}' class="ui button">retour</a>
    </p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.
        Accusantium alias commodi deserunt eius eligendi esse facere,
        impedit labore nemo placeat repudiandae tenetur, ut? Ea illo,
        molestiae officia quo similique voluptate.</p>
{% endblock %}